global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'bobeat-server:8080' ]

  - job_name: 'nginx'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]